### ISSUE TITLE
Remove "Get in touch" on Contact Page?

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/seaborne#36]
Design question for @brendonsanctuary! 

Should the “Get in touch” button top right corner disappear on the contact page? Clicking it just refreshes the page

![image.png](https://images.zenhubusercontent.com/5993211d8f62dc7798c2dc29/f5481799-c2b1-4fd1-89ff-ceb936668f1c)

**Comment by chrismekim** [comment]
Closed because https://twist.com/a/133876/ch/352305/t/1893927/c/61192955
